"""empty message

Revision ID: 37604fc01cec
Revises: 
Create Date: 2020-11-26 19:35:12.724091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37604fc01cec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paginas',
    sa.Column('id_paginas', sa.Integer(), nullable=False),
    sa.Column('nombre_pagina', sa.String(length=50), nullable=False),
    sa.Column('ruta_pagina', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_paginas')
    )
    op.create_table('restaurante',
    sa.Column('id_restaurante', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('cantidad_maxima', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_restaurante'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('roles',
    sa.Column('id_roles', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id_roles')
    )
    op.create_table('lista_de_espera',
    sa.Column('id_lista', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('numero_mesas', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id_restaurante'], ),
    sa.PrimaryKeyConstraint('id_lista'),
    sa.UniqueConstraint('restaurante_id')
    )
    op.create_table('persona',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('roles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id_roles'], ),
    sa.PrimaryKeyConstraint('id_persona'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('username')
    )
    op.create_table('relacion',
    sa.Column('id_relacion', sa.Integer(), nullable=False),
    sa.Column('id_paginas', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_paginas'], ['paginas.id_paginas'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id_roles'], ),
    sa.PrimaryKeyConstraint('id_relacion')
    )
    op.create_table('inscripcion',
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.Column('id_lista', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_lista'], ['lista_de_espera.id_lista'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id_persona'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscripcion')
    op.drop_table('relacion')
    op.drop_table('persona')
    op.drop_table('lista_de_espera')
    op.drop_table('roles')
    op.drop_table('restaurante')
    op.drop_table('paginas')
    # ### end Alembic commands ###
