"""empty message

Revision ID: 477c5a058bde
Revises: 
Create Date: 2020-11-28 14:51:33.400939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477c5a058bde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurante', sa.Column('capacidad_lista_espera', sa.Integer(), nullable=False))
    op.add_column('restaurante', sa.Column('direccion', sa.String(length=50), nullable=False))
    op.add_column('restaurante', sa.Column('telefono', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurante', 'telefono')
    op.drop_column('restaurante', 'direccion')
    op.drop_column('restaurante', 'capacidad_lista_espera')
    # ### end Alembic commands ###
