"""empty message

Revision ID: 8191b5778803
Revises: 37604fc01cec
Create Date: 2020-11-26 20:47:23.895545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8191b5778803'
down_revision = '37604fc01cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('telefono', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'telefono')
    # ### end Alembic commands ###
